name: Publish to Github pages
on:
    push:
        branches:
            - master
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout at master
              uses: actions/checkout@master
            - name: Setup NodeJs
              uses: actions/setup-node@master
              with:
                node-version: 10.0.0
            - run: npm install
            - run: npm deploy
            env:
                NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}